# Generated by Django 6.0.1 on 2026-01-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PetVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_vaccinations', to='core.pet')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaccinationtype')),
            ],
            options={
                'unique_together': {('pet', 'vaccination')},
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, related_name='pets', through='core.PetVaccination', to='core.vaccinationtype'),
        ),
        migrations.DeleteModel(
            name='Vaccination',
        ),
    ]
