# Generated by Django 6.0.1 on 2026-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vaccinationtype_petvaccination_pet_vaccinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
